-- 1. Display all the records available in the Customers table.
SELECT * FROM Customers;

-- 2. Retrieve all the records from the Products table.
SELECT * FROM Products;

-- 3. Display all the records stored in the Orders table.
SELECT * FROM Orders;

-- 4. Display only the Customer ID, Customer Name, and City from the Customers table.
SELECT customer_id, customer_name, city FROM Customers;

-- 5. Display only the Product ID, Product Name, and Unit Price from the Products table.
SELECT product_id, product_name, unit_price FROM Products;

-- 6. Retrieve the list of all unique cities where customers are located.
SELECT DISTINCT city FROM Customers;

-- 7. Display the complete details of customers who belong to the city Hyderabad.
SELECT * FROM Customers WHERE city = 'Hyderabad';

-- 8. Retrieve the complete details of customers whose age is greater than 25 years.
SELECT * FROM Customers WHERE age > 25;

-- 9. Display all products whose Unit Price is greater than ₹1,000.
SELECT * FROM Products WHERE unit_price > 1000;

-- 10. Display all products whose Status is marked as Active.
SELECT * FROM Products WHERE status = 'Active';

-- 11. Retrieve all orders where the ordered Quantity is greater than 2.
SELECT * FROM Orders WHERE quantity > 2;

-- 12. Display all orders whose Order Status is Delivered.
SELECT * FROM Orders WHERE order_status = 'Delivered';

-- 13. Retrieve all orders whose Order Status is Cancelled.
SELECT * FROM Orders WHERE order_status = 'Cancelled';

-- 14. Display all customer details sorted alphabetically by Customer Name in ascending order.
SELECT * FROM Customers ORDER BY customer_name ASC;

-- 15. Display all products sorted by Unit Price in descending order.
SELECT * FROM Products ORDER BY unit_price DESC;

-- 16. Display all orders sorted by Order Date from the latest order to the oldest order.
SELECT * FROM Orders ORDER BY order_date DESC;

-- 17. Retrieve only the first 10 records from the Orders table.
SELECT * FROM Orders LIMIT 10;

-- 18. Calculate the total number of customers available in the Customers table.
SELECT COUNT(*) AS total_customers FROM Customers;

-- 19. Calculate the total number of products available in the Products table.
SELECT COUNT(*) AS total_products FROM Products;

-- 20. Calculate the total number of orders placed by customers.
SELECT COUNT(*) AS total_orders FROM Orders;

-- 21. Determine the highest Unit Price available in the Products table.
SELECT MAX(unit_price) AS highest_unit_price FROM Products;

-- 22. Determine the lowest Unit Price available in the Products table.
SELECT MIN(unit_price) AS lowest_unit_price FROM Products;

-- 23. Calculate the average Unit Price of all products.
SELECT AVG(unit_price) AS average_unit_price FROM Products;

-- 24. Calculate the total sales amount generated from all customer orders.
SELECT SUM(total_amount) AS total_sales_amount FROM Orders;

-- 25. Calculate the average order amount across all customer orders.
SELECT AVG(total_amount) AS average_order_amount FROM Orders;

-- 26. Display all products that belong to the Electronics category.
SELECT * FROM Products WHERE category = 'Electronics';

-- 27. Display all products that belong to the Fashion category.
SELECT * FROM Products WHERE category = 'Fashion';

-- 28. Retrieve all customer details where the Customer Name starts with the letter 'A'.
SELECT * FROM Customers WHERE customer_name LIKE 'A%';

-- 29. Retrieve all customer details where the Customer Name ends with the letter 'N'.
SELECT * FROM Customers WHERE customer_name LIKE '%n' OR customer_name LIKE '%N';

-- 30. Display all customers who registered after 01 January 2024.
SELECT * FROM Customers WHERE registration_date > '2024-01-01';

-- 31. Calculate the total purchase amount made by each customer and display the results in descending order of total purchase value.
SELECT c.customer_id, c.customer_name, SUM(o.total_amount) AS total_purchase_amount
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_purchase_amount DESC;

-- 32. Calculate the total revenue generated by each product, including the product name and total quantity sold.
SELECT p.product_id, p.product_name, SUM(o.quantity) AS total_quantity_sold, SUM(o.total_amount) AS total_revenue
FROM Products p
JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name;

-- 33. Calculate the total sales generated from each city based on customer orders.
SELECT c.city, SUM(o.total_amount) AS total_sales
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.city;

-- 34. Determine the total quantity sold for each product and display the results from highest to lowest quantity sold.
SELECT p.product_id, p.product_name, SUM(o.quantity) AS total_quantity_sold
FROM Products p
JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC;

-- 35. Identify the top five customers who have spent the highest total purchase amount across all their orders.
SELECT c.customer_id, c.customer_name, SUM(o.total_amount) AS total_spent
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC
LIMIT 5;

-- 36. Identify the top five best-selling products based on the total quantity sold.
SELECT p.product_id, p.product_name, SUM(o.quantity) AS total_quantity_sold
FROM Products p
JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 5;

-- 37. Determine the highest order amount, along with the customer name and product name associated with that order.
SELECT c.customer_name, p.product_name, o.total_amount
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
JOIN Products p ON o.product_id = p.product_id
ORDER BY o.total_amount DESC
LIMIT 1;

-- 38. Determine the second highest order amount without using the LIMIT 1 approach.
SELECT MAX(total_amount) AS second_highest_order_amount
FROM Orders
WHERE total_amount < (SELECT MAX(total_amount) FROM Orders);

-- 39. Calculate the average order amount for each payment method and display the results in descending order.
SELECT payment_method, AVG(total_amount) AS avg_order_amount
FROM Orders
GROUP BY payment_method
ORDER BY avg_order_amount DESC;

-- 40. Calculate the total revenue generated by each product category.
SELECT p.category, SUM(o.total_amount) AS total_revenue
FROM Products p
JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.category;

-- 41. Identify all customers who have never placed an order.
SELECT c.*
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- 42. Identify all products that have never been purchased by any customer.
SELECT p.*
FROM Products p
LEFT JOIN Orders o ON p.product_id = o.product_id
WHERE o.order_id IS NULL;

-- 43. Generate a monthly sales report showing the month, total number of orders, and total revenue generated.
SELECT 
    TO_CHAR(order_date, 'YYYY-MM') AS month,
    COUNT(order_id) AS total_orders,
    SUM(total_amount) AS total_revenue
FROM Orders
GROUP BY TO_CHAR(order_date, 'YYYY-MM')
ORDER BY month;

-- 44. Determine which Salesperson generated the highest revenue, along with the total revenue generated.
SELECT salesperson, SUM(total_amount) AS total_revenue
FROM Orders
GROUP BY salesperson
ORDER BY total_revenue DESC
LIMIT 1;

-- 45. Identify the customer who has placed the maximum number of orders.
SELECT c.customer_id, c.customer_name, COUNT(o.order_id) AS total_orders
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC
LIMIT 1;

-- 46. Calculate the average product rating for each product category and display the categories in descending order of average rating.
SELECT category, AVG(rating) AS avg_rating
FROM Products
GROUP BY category
ORDER BY avg_rating DESC;

-- 47. Retrieve all products whose Stock Quantity is less than 20 units.
SELECT * FROM Products WHERE stock_quantity < 20;

-- 48. Calculate the percentage contribution of each product category to the overall sales revenue.
SELECT 
    p.category,
    SUM(o.total_amount) AS category_revenue,
    ROUND((SUM(o.total_amount) * 100.0 / (SELECT SUM(total_amount) FROM Orders)), 2) AS percentage_contribution
FROM Products p
JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.category;

-- 49. Rank all customers based on their total purchase amount using PostgreSQL window functions such as RANK() or DENSE_RANK().
SELECT 
    c.customer_id,
    c.customer_name,
    SUM(o.total_amount) AS total_purchase_amount,
    DENSE_RANK() OVER (ORDER BY SUM(o.total_amount) DESC) AS customer_rank
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;

-- 50. Write a comprehensive SQL query using appropriate INNER JOIN, LEFT JOIN, GROUP BY, and ORDER BY clauses to generate a report containing Customer Name, Product Name, Order Date, Quantity, Discount Percentage, Total Amount, Payment Method, Order Status, Salesperson, Customer City, and Product Category. Display the report in descending order based on the Order Date.
SELECT 
    c.customer_name,
    p.product_name,
    o.order_date,
    o.quantity,
    o.discount_percent,
    o.total_amount,
    o.payment_method,
    o.order_status,
    o.salesperson,
    c.city AS customer_city,
    p.category AS product_category
FROM Orders o
INNER JOIN Customers c ON o.customer_id = c.customer_id
LEFT JOIN Products p ON o.product_id = p.product_id
ORDER BY o.order_date DESC;